version: '3.1'
services:
  app:
    image: deployify-apiserver:latest
    ports:
      - '8080:8080'
    env_file: '.env'
    depends_on:
      - db
  db:
    container_name: mypostgres
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
